# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'settingjYOjGY.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Setting(object):
    def setupUi(self, Setting):
        if not Setting.objectName():
            Setting.setObjectName(u"Setting")
        Setting.resize(828, 633)
        Setting.setMinimumSize(QSize(828, 633))
        Setting.setMaximumSize(QSize(828, 633))
        self.tabWidget = QTabWidget(Setting)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 30, 811, 591))
        self.tabWidget.setMinimumSize(QSize(0, 100))
        self.tabWidget.setMaximumSize(QSize(9999, 9999))
        font = QFont()
        font.setFamily(u"\ub098\ub214\uc2a4\ud018\uc5b4")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QCursor(Qt.ArrowCursor))
        self.tabWidget.setStyleSheet(u"QTabBar {background: none; color:white;}\n"
"QTabBar::tab {height: 55px; width: 200px; color: f0f0ff;}\n"
"QTabBar::tab::selected {background: #a0a0a0;}\n"
"QTabWidget::pane {border: 0;}\n"
"")
        self.tabWidget.setTabShape(QTabWidget.Triangular)
        self.tabWidget.setIconSize(QSize(20, 16))
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        font1 = QFont()
        font1.setFamily(u"\ub098\ub214\uc2a4\ud018\uc5b4")
        self.tab_5.setFont(font1)
        self.tab_5.setStyleSheet(u"background: #444444;")
        self.spot_name_lbl = QLabel(self.tab_5)
        self.spot_name_lbl.setObjectName(u"spot_name_lbl")
        self.spot_name_lbl.setGeometry(QRect(24, 90, 131, 25))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spot_name_lbl.sizePolicy().hasHeightForWidth())
        self.spot_name_lbl.setSizePolicy(sizePolicy)
        self.spot_name_lbl.setMaximumSize(QSize(131, 25))
        font2 = QFont()
        font2.setFamily(u"\ub098\ub214\uc2a4\ud018\uc5b4")
        font2.setPointSize(10)
        self.spot_name_lbl.setFont(font2)
        self.spot_name_lbl.setStyleSheet(u"color: white;")
        self.spot_id = QLineEdit(self.tab_5)
        self.spot_id.setObjectName(u"spot_id")
        self.spot_id.setGeometry(QRect(194, 40, 140, 20))
        self.spot_id.setMaximumSize(QSize(140, 20))
        self.spot_id.setFont(font1)
        self.spot_id.setStyleSheet(u"background: #ffffff; color: black;")
        self.spot_name = QLineEdit(self.tab_5)
        self.spot_name.setObjectName(u"spot_name")
        self.spot_name.setGeometry(QRect(194, 90, 140, 20))
        self.spot_name.setMaximumSize(QSize(140, 20))
        self.spot_name.setFont(font1)
        self.spot_name.setStyleSheet(u"background: #ffffff; color: black;")
        self.spot_id_lbl = QLabel(self.tab_5)
        self.spot_id_lbl.setObjectName(u"spot_id_lbl")
        self.spot_id_lbl.setGeometry(QRect(24, 40, 131, 25))
        sizePolicy.setHeightForWidth(self.spot_id_lbl.sizePolicy().hasHeightForWidth())
        self.spot_id_lbl.setSizePolicy(sizePolicy)
        self.spot_id_lbl.setMaximumSize(QSize(131, 25))
        self.spot_id_lbl.setFont(font2)
        self.spot_id_lbl.setStyleSheet(u"color: white;")
        self.btn = QPushButton(self.tab_5)
        self.btn.setObjectName(u"btn")
        self.btn.setGeometry(QRect(305, 160, 91, 31))
        self.btn.setFont(font1)
        self.btn.setStyleSheet(u"color: black; background: #999;")
        self.user_pwd = QLineEdit(self.tab_5)
        self.user_pwd.setObjectName(u"user_pwd")
        self.user_pwd.setGeometry(QRect(547, 90, 140, 20))
        self.user_pwd.setFont(font1)
        self.user_pwd.setStyleSheet(u"background: #ffffff; color: black;")
        self.user_pwd_lbl = QLabel(self.tab_5)
        self.user_pwd_lbl.setObjectName(u"user_pwd_lbl")
        self.user_pwd_lbl.setGeometry(QRect(400, 90, 100, 25))
        sizePolicy.setHeightForWidth(self.user_pwd_lbl.sizePolicy().hasHeightForWidth())
        self.user_pwd_lbl.setSizePolicy(sizePolicy)
        self.user_pwd_lbl.setFont(font2)
        self.user_pwd_lbl.setStyleSheet(u"color: white;")
        self.user_id_lbl = QLabel(self.tab_5)
        self.user_id_lbl.setObjectName(u"user_id_lbl")
        self.user_id_lbl.setGeometry(QRect(400, 40, 114, 25))
        sizePolicy.setHeightForWidth(self.user_id_lbl.sizePolicy().hasHeightForWidth())
        self.user_id_lbl.setSizePolicy(sizePolicy)
        self.user_id_lbl.setMinimumSize(QSize(111, 25))
        self.user_id_lbl.setFont(font2)
        self.user_id_lbl.setStyleSheet(u"color: white;")
        self.user_id = QLineEdit(self.tab_5)
        self.user_id.setObjectName(u"user_id")
        self.user_id.setGeometry(QRect(547, 40, 140, 20))
        self.user_id.setFont(font1)
        self.user_id.setStyleSheet(u"background: #ffffff; color: black;")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tab_6.setStyleSheet(u"background: #444444;")
        self.btn_2 = QPushButton(self.tab_6)
        self.btn_2.setObjectName(u"btn_2")
        self.btn_2.setGeometry(QRect(305, 100, 91, 31))
        self.btn_2.setFont(font1)
        self.btn_2.setStyleSheet(u"color: black; background: #999;")
        self.api_path_lbl = QLabel(self.tab_6)
        self.api_path_lbl.setObjectName(u"api_path_lbl")
        self.api_path_lbl.setGeometry(QRect(400, 40, 71, 25))
        sizePolicy.setHeightForWidth(self.api_path_lbl.sizePolicy().hasHeightForWidth())
        self.api_path_lbl.setSizePolicy(sizePolicy)
        self.api_path_lbl.setMaximumSize(QSize(71, 25))
        self.api_path_lbl.setFont(font2)
        self.api_path_lbl.setStyleSheet(u"color: white;")
        self.save_path = QLineEdit(self.tab_6)
        self.save_path.setObjectName(u"save_path")
        self.save_path.setGeometry(QRect(194, 40, 140, 20))
        self.save_path.setMaximumSize(QSize(150, 20))
        self.save_path.setFont(font1)
        self.save_path.setStyleSheet(u"background: #ffffff; color: black;")
        self.api_path = QLineEdit(self.tab_6)
        self.api_path.setObjectName(u"api_path")
        self.api_path.setGeometry(QRect(547, 40, 140, 20))
        self.api_path.setMaximumSize(QSize(140, 20))
        self.api_path.setFont(font1)
        self.api_path.setStyleSheet(u"background: #ffffff; color: black;")
        self.save_path_lbl = QLabel(self.tab_6)
        self.save_path_lbl.setObjectName(u"save_path_lbl")
        self.save_path_lbl.setGeometry(QRect(24, 40, 131, 25))
        sizePolicy.setHeightForWidth(self.save_path_lbl.sizePolicy().hasHeightForWidth())
        self.save_path_lbl.setSizePolicy(sizePolicy)
        self.save_path_lbl.setFont(font2)
        self.save_path_lbl.setStyleSheet(u"color: white;")
        self.tabWidget.addTab(self.tab_6, "")
        self.logo_btn = QPushButton(Setting)
        self.logo_btn.setObjectName(u"logo_btn")
        self.logo_btn.setGeometry(QRect(720, 10, 70, 70))
        self.logo_btn.setStyleSheet(u"background-color: rgb(240, 240, 240);\n"
"border: none")

        self.retranslateUi(Setting)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Setting)
    # setupUi

    def retranslateUi(self, Setting):
        Setting.setWindowTitle(QCoreApplication.translate("Setting", u"Form", None))
        self.spot_name_lbl.setText(QCoreApplication.translate("Setting", u"\uc0ac\uc5c5\uc7a5 \uc774\ub984", None))
        self.spot_id_lbl.setText(QCoreApplication.translate("Setting", u"\uc0ac\uc5c5\uc7a5ID", None))
        self.btn.setText(QCoreApplication.translate("Setting", u"\uc801\uc6a9", None))
        self.user_pwd_lbl.setText(QCoreApplication.translate("Setting", u"\uacc4\uc815 PWD", None))
        self.user_id_lbl.setText(QCoreApplication.translate("Setting", u"\uacc4\uc815 ID ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("Setting", u"Config \uc218\uc815", None))
        self.btn_2.setText(QCoreApplication.translate("Setting", u"\uc801\uc6a9", None))
        self.api_path_lbl.setText(QCoreApplication.translate("Setting", u"api \uc8fc\uc18c", None))
        self.save_path_lbl.setText(QCoreApplication.translate("Setting", u"\uc800\uc7a5 \uacbd\ub85c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("Setting", u"Setting \uc218\uc815", None))
        self.logo_btn.setText("")
    # retranslateUi

